// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "e1m0re/loyalty-srv/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: ctx, userID
func (_m *AccountRepository) AddAccount(ctx context.Context, userID models.UserID) (*models.Account, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddAccount")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) (*models.Account, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) *models.Account); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddAccountChange provides a mock function with given fields: ctx, accountID, sum, orderNum
func (_m *AccountRepository) AddAccountChange(ctx context.Context, accountID models.AccountID, sum float64, orderNum models.OrderNum) (*models.AccountChanges, error) {
	ret := _m.Called(ctx, accountID, sum, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for AddAccountChange")
	}

	var r0 *models.AccountChanges
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountID, float64, models.OrderNum) (*models.AccountChanges, error)); ok {
		return rf(ctx, accountID, sum, orderNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountID, float64, models.OrderNum) *models.AccountChanges); ok {
		r0 = rf(ctx, accountID, sum, orderNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccountChanges)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AccountID, float64, models.OrderNum) error); ok {
		r1 = rf(ctx, accountID, sum, orderNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByUserID provides a mock function with given fields: ctx, userID
func (_m *AccountRepository) GetAccountByUserID(ctx context.Context, userID models.UserID) (*models.Account, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByUserID")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) (*models.Account, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) *models.Account); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawalsList provides a mock function with given fields: ctx, accountID
func (_m *AccountRepository) GetWithdrawalsList(ctx context.Context, accountID models.AccountID) (*[]models.Withdrawal, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsList")
	}

	var r0 *[]models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountID) (*[]models.Withdrawal, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountID) *[]models.Withdrawal); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AccountID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawnTotalSum provides a mock function with given fields: ctx, accountID
func (_m *AccountRepository) GetWithdrawnTotalSum(ctx context.Context, accountID models.AccountID) (int, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawnTotalSum")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountID) (int, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountID) int); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AccountID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAccount provides a mock function with given fields: ctx, account
func (_m *AccountRepository) UpdateAccount(ctx context.Context, account *models.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
