// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "e1m0re/loyalty-srv/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// AccountsService is an autogenerated mock type for the AccountsService type
type AccountsService struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: ctx, id
func (_m *AccountsService) CreateAccount(ctx context.Context, id models.UserID) (*models.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) (*models.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) *models.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByUserID provides a mock function with given fields: ctx, userID
func (_m *AccountsService) GetAccountByUserID(ctx context.Context, userID models.UserID) (*models.Account, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByUserID")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) (*models.Account, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) *models.Account); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountInfo provides a mock function with given fields: ctx, account
func (_m *AccountsService) GetAccountInfo(ctx context.Context, account *models.Account) (*models.AccountInfo, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountInfo")
	}

	var r0 *models.AccountInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) (*models.AccountInfo, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) *models.AccountInfo); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccountInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Account) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithdrawals provides a mock function with given fields: ctx, account
func (_m *AccountsService) GetWithdrawals(ctx context.Context, account *models.Account) (*[]models.Withdrawal, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 *[]models.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) (*[]models.Withdrawal, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) *[]models.Withdrawal); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Account) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: ctx, account, amount, orderNum
func (_m *AccountsService) UpdateBalance(ctx context.Context, account models.Account, amount float64, orderNum models.OrderNum) (*models.Account, error) {
	ret := _m.Called(ctx, account, amount, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Account, float64, models.OrderNum) (*models.Account, error)); ok {
		return rf(ctx, account, amount, orderNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Account, float64, models.OrderNum) *models.Account); ok {
		r0 = rf(ctx, account, amount, orderNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Account, float64, models.OrderNum) error); ok {
		r1 = rf(ctx, account, amount, orderNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountsService creates a new instance of AccountsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsService {
	mock := &AccountsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
