// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "e1m0re/loyalty-srv/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// OrdersService is an autogenerated mock type for the OrdersService type
type OrdersService struct {
	mock.Mock
}

// GetLoadedOrdersByUserId provides a mock function with given fields: ctx, id
func (_m *OrdersService) GetLoadedOrdersByUserId(ctx context.Context, id models.UserId) ([]models.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLoadedOrdersByUserId")
	}

	var r0 []models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserId) ([]models.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserId) []models.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserId) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadOrder provides a mock function with given fields: ctx, orderNum
func (_m *OrdersService) LoadOrder(ctx context.Context, orderNum models.OrderNum) (*models.Order, bool, error) {
	ret := _m.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for LoadOrder")
	}

	var r0 *models.Order
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderNum) (*models.Order, bool, error)); ok {
		return rf(ctx, orderNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderNum) *models.Order); ok {
		r0 = rf(ctx, orderNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OrderNum) bool); ok {
		r1 = rf(ctx, orderNum)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.OrderNum) error); ok {
		r2 = rf(ctx, orderNum)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateOrder provides a mock function with given fields: ctx, id, status, accrual
func (_m *OrdersService) UpdateOrder(ctx context.Context, id models.OrderId, status models.OrdersStatus, accrual int) (models.Order, error) {
	ret := _m.Called(ctx, id, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderId, models.OrdersStatus, int) (models.Order, error)); ok {
		return rf(ctx, id, status, accrual)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderId, models.OrdersStatus, int) models.Order); ok {
		r0 = rf(ctx, id, status, accrual)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OrderId, models.OrdersStatus, int) error); ok {
		r1 = rf(ctx, id, status, accrual)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateNumber provides a mock function with given fields: ctx, orderNum
func (_m *OrdersService) ValidateNumber(ctx context.Context, orderNum models.OrderNum) (bool, error) {
	ret := _m.Called(ctx, orderNum)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNumber")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderNum) (bool, error)); ok {
		return rf(ctx, orderNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OrderNum) bool); ok {
		r0 = rf(ctx, orderNum)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OrderNum) error); ok {
		r1 = rf(ctx, orderNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrdersService creates a new instance of OrdersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdersService {
	mock := &OrdersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
